version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  pokemon_app:
    build: .
    container_name: pokemon_app
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - ollama
    environment:
      - LLM_MODEL_VERSION=${LLM_MODEL_VERSION}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - OLLAMA_URL=${OLLAMA_URL}
      - LOG_LEVEL=DEBUG
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  ollama:
    image: ollama/ollama:0.5.7 
    container_name: ollama
    volumes:
      - ollama:/root/.ollama  
      - ./ollama_entrypoint.sh:/ollama_entrypoint.sh 
    ports:
      - "11434:11434"
    environment:
      - LLM_MODEL_VERSION=${LLM_MODEL_VERSION} 
    entrypoint: ["/bin/bash", "/ollama_entrypoint.sh"] 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:11434 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  esdata:
    driver: local
  ollama:
    driver: local
